import { NoteLength, ScaleType } from "@tspro/web-music-score/theory";
import { MDocument, NoteAnchor, Navigation, Annotation, StaffPreset, Stem, DocumentBuilder, Connective } from "@tspro/web-music-score/score";

/** @public */
export function createAndanteByDiabelli(): MDocument {
    return new DocumentBuilder(StaffPreset.GuitarTreble)

        .setHeader("Andante", "A. Diabelli")

        .addMeasure()
        .setKeySignature("D", ScaleType.Major)
        .setTimeSignature("3/4")
        .setTempo(80)
        .addRest(0, NoteLength.Eighth, { staffPos: "G4" }).addAnnotation(Annotation.Dynamics, "p")
        .addNote(0, "F#4", NoteLength.Eighth, { stem: Stem.Up })
        .addNote(0, "G4", NoteLength.Eighth).addConnective(Connective.Slur, 2, NoteAnchor.Below)
        .addNote(0, "F#4", NoteLength.Eighth)
        .addNote(0, "E4", NoteLength.Eighth)
        .addNote(0, "D4", NoteLength.Eighth)
        .addNote(1, "D3", NoteLength.Half, { dotted: true, stem: Stem.Down })

        .addMeasure()
        .addNote(0, "C#4", NoteLength.Eighth).addConnective(Connective.Slur, 2, NoteAnchor.Below)
        .addNote(0, "D4", NoteLength.Eighth)
        .addNote(0, "E4", NoteLength.Eighth)
        .addNote(0, "F#4", NoteLength.Eighth)
        .addNote(0, "G4", NoteLength.Quarter)
        .addNote(1, "A2", NoteLength.Half, { dotted: true })

        .addMeasure()
        .addRest(0, NoteLength.Eighth, { staffPos: "B3" }).addAnnotation(Annotation.Dynamics, "f")
        .addNote(0, "A3", NoteLength.Eighth)
        .addNote(0, "G#3", NoteLength.Eighth).addConnective(Connective.Slur, 2, NoteAnchor.Below)
        .addNote(0, "A3", NoteLength.Eighth)
        .addNote(0, "B3", NoteLength.Eighth)
        .addNote(0, "C#4", NoteLength.Eighth)
        .addNote(1, "A2", NoteLength.Half, { dotted: true })
        .endRow()

        .addMeasure()
        .addNote(0, "D4", NoteLength.Eighth)
        .addNote(0, "E4", NoteLength.Eighth)
        .addNote(0, "F#4", NoteLength.Eighth)
        .addNote(0, "G4", NoteLength.Eighth)
        .addNote(0, "A4", NoteLength.Quarter)
        .addNote(1, "D3", NoteLength.Half, { dotted: true })

        .addMeasure()
        .addRest(0, NoteLength.Eighth, { staffPos: "G4" }).addAnnotation(Annotation.Dynamics, "p")
        .addNote(0, "F#4", NoteLength.Eighth)
        .addNote(0, "G4", NoteLength.Eighth).addConnective(Connective.Slur, 2, NoteAnchor.Below)
        .addNote(0, "F#4", NoteLength.Eighth)
        .addNote(0, "E4", NoteLength.Eighth)
        .addNote(0, "D4", NoteLength.Eighth)
        .addNote(1, "D3", NoteLength.Half, { dotted: true })

        .addMeasure()
        .addNote(0, "C#4", NoteLength.Eighth).addConnective(Connective.Slur, 2, NoteAnchor.Below)
        .addNote(0, "D4", NoteLength.Eighth)
        .addNote(0, "E4", NoteLength.Eighth)
        .addNote(0, "F#4", NoteLength.Eighth)
        .addNote(0, "G4", NoteLength.Quarter)
        .addNote(1, "A2", NoteLength.Half, { dotted: true })
        .endRow()

        .addMeasure()
        .addRest(0, NoteLength.Eighth, { staffPos: "B3" }).addAnnotation(Annotation.Dynamics, "f")
        .addNote(0, "A3", NoteLength.Eighth)
        .addNote(0, "G#3", NoteLength.Eighth).addConnective(Connective.Slur, 2, NoteAnchor.Below)
        .addNote(0, "A3", NoteLength.Eighth)
        .addNote(0, "B3", NoteLength.Eighth)
        .addNote(0, "C#4", NoteLength.Eighth)
        .addNote(1, "A2", NoteLength.Half, { dotted: true })

        .addMeasure()
        .addNote(0, "D4", NoteLength.Quarter)
        .addRest(1, NoteLength.Quarter, { staffPos: "D3" })
        .addNote(0, "D3", NoteLength.Quarter) // Stem up...
        .addNote(1, "D3", NoteLength.Quarter) // ...and down
        .addRest(1, NoteLength.Quarter, { staffPos: "B3" })
        .addNavigation(Navigation.EndRepeat)

        .addMeasure()
        .addRest(0, NoteLength.Eighth, { staffPos: "D4" }).addAnnotation(Annotation.Dynamics, "f")
        .addNote(0, "D4", NoteLength.Eighth)
        .addNote(0, "E4", NoteLength.Eighth).addConnective(Connective.Slur, 2, NoteAnchor.Below)
        .addNote(0, "D4", NoteLength.Eighth)
        .addNote(0, "C#4", NoteLength.Eighth)
        .addNote(0, "B3", NoteLength.Eighth)
        .addNote(1, "E2", NoteLength.Half, { dotted: true })
        .endRow()

        .addMeasure()
        .addNote(0, "C#4", NoteLength.Eighth).addConnective(Connective.Slur, 2, NoteAnchor.Below)
        .addNote(0, "D4", NoteLength.Eighth)
        .addNote(0, "E4", NoteLength.Eighth)
        .addNote(0, "F#4", NoteLength.Eighth)
        .addNote(0, "E4", NoteLength.Quarter)
        .addNote(1, "A2", NoteLength.Half, { dotted: true })

        .addMeasure()
        .addRest(0, NoteLength.Eighth, { staffPos: "B3" }).addAnnotation(Annotation.Dynamics, "p")
        .addNote(0, "E3", NoteLength.Eighth)
        .addNote(0, "D#3", NoteLength.Eighth).addConnective(Connective.Slur, 2, NoteAnchor.Below)
        .addNote(0, "E3", NoteLength.Eighth)
        .addNote(0, "F#3", NoteLength.Eighth)
        .addNote(0, "G#3", NoteLength.Eighth)
        .addNote(1, "E2", NoteLength.Half, { dotted: true })

        .addMeasure()
        .addNote(0, "A3", NoteLength.Eighth).addConnective(Connective.Slur, 2, NoteAnchor.Below)
        .addNote(0, "G#3", NoteLength.Eighth)
        .addNote(0, "A3", NoteLength.Eighth)
        .addNote(0, "B3", NoteLength.Eighth)
        .addNote(0, "C#4", NoteLength.Quarter)
        .addNote(1, "A2", NoteLength.Half, { dotted: true })
        .endRow()

        .addMeasure()
        .addRest(0, NoteLength.Eighth, { staffPos: "G4" }).addAnnotation(Annotation.Dynamics, "f")
        .addNote(0, "G4", NoteLength.Eighth)
        .addNote(0, "A4", NoteLength.Eighth).addConnective(Connective.Slur, 2, NoteAnchor.Below)
        .addNote(0, "G4", NoteLength.Eighth)
        .addNote(0, "F#4", NoteLength.Eighth)
        .addNote(0, "E4", NoteLength.Eighth)
        .addNote(1, "A2", NoteLength.Half, { dotted: true })

        .addMeasure()
        .addNote(0, "D4", NoteLength.Eighth)
        .addNote(0, "C#4", NoteLength.Eighth)
        .addNote(0, "D4", NoteLength.Eighth)
        .addNote(0, "E4", NoteLength.Eighth)
        .addNote(0, "F#4", NoteLength.Quarter)
        .addNote(1, "D3", NoteLength.Half, { dotted: true })

        .addMeasure()
        .addRest(0, NoteLength.Eighth, { staffPos: "B3" }).addAnnotation(Annotation.Dynamics, "ff")
        .addNote(0, "A3", NoteLength.Eighth)
        .addNote(0, "G#3", NoteLength.Eighth).addConnective(Connective.Slur, 2, NoteAnchor.Below)
        .addNote(0, "A3", NoteLength.Eighth)
        .addNote(0, "B3", NoteLength.Eighth)
        .addNote(0, "C#4", NoteLength.Eighth)
        .addNote(1, "A2", NoteLength.Half, { dotted: true })

        .addMeasure()
        .addNote(0, "D4", NoteLength.Quarter)
        .addRest(1, NoteLength.Quarter, { staffPos: "D3" })
        .addNote(0, "D3", NoteLength.Quarter) // Stem up... 
        .addNote(1, "D3", NoteLength.Quarter) // ...and down
        .addRest(1, NoteLength.Quarter, { staffPos: "B3" })
        .endSong()

        .getDocument();
}
