import { MDocument, DocumentBuilder } from "web-music-score/score";

/**
 * Create Greensleeves music piece.<br />
 * <br />
 * Source: https://musescore.com/aaron_dc/scores/6167495
 * 
 * @returns - Music document.
 */
export function createGreensleeves(): MDocument {
    return new DocumentBuilder()
        .setScoreConfiguration("guitarTreble")
        .setHeader("Greensleeves")

        .addMeasure()
        .setKeySignature("C", "Major")
        .setTimeSignature("6/8")
        .setTempo(140)
        .addNote(0, "A3", "8n")

        .addMeasure()
        .addAnnotation("startRepeat")
        .addNote(0, "C4", "4n", { stem: "up" }).addAnnotation("Am", "chordLabel")
        .addNote(0, "D4", "8n")
        .addNote(0, "E4", "8.")
        .addNote(0, "F4", "16n")
        .addNote(0, "E4", "8n")
        .addNote(1, "A2", "8n", { stem: "down" })
        .addNote(1, "E3", "4n")
        .addNote(1, "A2", "8n")
        .addNote(1, "E3", "4n")

        .addMeasure()
        .addNote(0, "D4", "4n", { stem: "up" }).addAnnotation("G", "chordLabel")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8.").addAnnotation("Em", "chordLabel")
        .addNote(0, "A3", "16n")
        .addNote(0, "B3", "8n")
        .addNote(1, "G2", "8n", { stem: "down" })
        .addNote(1, "D3", "4n")
        .addNote(1, "E2", "8n")
        .addNote(1, "B2", "4n")

        .addMeasure()
        .addNote(0, "C4", "4n", { stem: "up" }).addAnnotation("Am", "chordLabel")
        .addNote(0, "A3", "8n")
        .addNote(0, "A3", "8.").addAnnotation("F", "chordLabel")
        .addNote(0, "G#3", "16n")
        .addNote(0, "A3", "8n")
        .addNote(1, "A2", "8n", { stem: "down" })
        .addNote(1, "E3", "4n")
        .addNote(1, "F2", "8n")
        .addNote(1, "A2", "4n")

        .addMeasure()
        .addNote(0, "B3", "4n", { stem: "up" }).addAnnotation("E", "chordLabel")
        .addNote(0, "G#3", "8n")
        .addNote(0, "E3", "4n")
        .addNote(0, "A3", "8n")
        .addNote(1, "E2", "8n", { stem: "down" })
        .addNote(1, "B2", "4n")
        .addNote(1, "E2", "8n")
        .addNote(1, "B2", "4n")
        .endRow()

        .addMeasure()
        .addNote(0, "C4", "4n", { stem: "up" }).addAnnotation("Am", "chordLabel")
        .addNote(0, "D4", "8n")
        .addNote(0, "E4", "8.")
        .addNote(0, "F4", "16n")
        .addNote(0, "E4", "8n")
        .addNote(1, "A2", "8n", { stem: "down" })
        .addNote(1, "E3", "4n")
        .addNote(1, "A2", "8n")
        .addNote(1, "E3", "4n")

        .addMeasure()
        .addNote(0, "D4", "4n", { stem: "up" }).addAnnotation("G", "chordLabel")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8.").addAnnotation("Em", "chordLabel")
        .addNote(0, "A3", "16n")
        .addNote(0, "B3", "8n")
        .addNote(1, "G2", "8n", { stem: "down" })
        .addNote(1, "D3", "4n")
        .addNote(1, "E2", "8n")
        .addNote(1, "B2", "4n")

        .addMeasure()
        .addNote(0, "C4", "8.", { stem: "up" }).addAnnotation("Am", "chordLabel")
        .addNote(0, "B3", "16n")
        .addNote(0, "A3", "8n")
        .addNote(0, "G#3", "8.").addAnnotation("E", "chordLabel")
        .addNote(0, "F#3", "16n")
        .addNote(0, "G#3", "8n")
        .addNote(1, "A2", "8n", { stem: "down" })
        .addNote(1, "E3", "4n")
        .addNote(1, "E2", "8n")
        .addNote(1, "B2", "4n")

        .addMeasure()
        .addNote(0, "A3", "4.", { stem: "up" }).addAnnotation("Am", "chordLabel")
        .addNote(0, "A3", "4.")
        .addNote(1, "A2", "8n", { stem: "down" })
        .addNote(1, "E3", "8n")
        .addNote(1, "C4", "8n")
        .addNote(1, "A2", "4.")
        .endRow()

        .addMeasure()
        .addChord(0, ["C3", "E3", "G3", "C4", "G4"], "4.", { arpeggio: "up", stem: "up" }).addAnnotation("C", "chordLabel")
        .addNote(0, "G4", "8.")
        .addNote(0, "F#4", "16n")
        .addNote(0, "E4", "8n")
        .addRest(1, "4.", { hide: true })
        .addNote(1, "C3", "8n", { stem: "down" })
        .addNote(1, "G3", "4n")

        .addMeasure()
        .addNote(0, "D4", "4n", { stem: "up" }).addAnnotation("G", "chordLabel")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8.").addAnnotation("Em", "chordLabel")
        .addNote(0, "A3", "16n")
        .addNote(0, "B3", "8n")
        .addNote(1, "G2", "8n", { stem: "down" })
        .addNote(1, "D3", "4n")
        .addNote(1, "E2", "8n")
        .addNote(1, "B2", "4n")

        .addMeasure()
        .addNote(0, "C4", "4n", { stem: "up" }).addAnnotation("Am", "chordLabel")
        .addNote(0, "A3", "8n")
        .addNote(0, "A3", "8.").addAnnotation("F", "chordLabel")
        .addNote(0, "G#3", "16n")
        .addNote(0, "A3", "8n")
        .addNote(1, "A2", "8n", { stem: "down" })
        .addNote(1, "E3", "4n")
        .addNote(1, "F2", "8n")
        .addNote(1, "A2", "4n")

        .addMeasure()
        .addNote(0, "B3", "4n", { stem: "up" }).addAnnotation("E", "chordLabel")
        .addNote(0, "G#3", "8n")
        .addNote(0, "E3", "4.")
        .addNote(1, "E2", "8n", { stem: "down" })
        .addNote(1, "B2", "4n")
        .addNote(1, "E2", "8n")
        .addNote(1, "B2", "8n")
        .addNote(1, "E3", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G4", "4.", { stem: "up" }).addAnnotation("C", "chordLabel")
        .addNote(0, "G4", "8.")
        .addNote(0, "F#4", "16n")
        .addNote(0, "E4", "8n")
        .addNote(1, "C3", "8n", { stem: "down" })
        .addNote(1, "G3", "8n")
        .addNote(1, "C4", "8n")
        .addNote(1, "C3", "8n")
        .addNote(1, "G3", "4n")

        .addMeasure()
        .addNote(0, "D4", "4n", { stem: "up" }).addAnnotation("G", "chordLabel")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8.").addAnnotation("Em", "chordLabel")
        .addNote(0, "A3", "16n")
        .addNote(0, "B3", "8n")
        .addNote(1, "G2", "8n", { stem: "down" })
        .addNote(1, "D3", "4n")
        .addNote(1, "E2", "8n")
        .addNote(1, "B2", "4n")

        .addMeasure()
        .addNote(0, "C4", "8.", { stem: "up" }).addAnnotation("Am", "chordLabel")
        .addNote(0, "B3", "16n")
        .addNote(0, "A3", "8n")
        .addNote(0, "G#3", "8.").addAnnotation("E", "chordLabel")
        .addNote(0, "F#3", "16n")
        .addNote(0, "G#3", "8n")
        .addNote(1, "A2", "8n", { stem: "down" })
        .addNote(1, "E3", "4n")
        .addNote(1, "E2", "8n")
        .addNote(1, "B2", "4n")

        .addMeasure()
        .addAnnotation("ending", { endingPassages: 1 })
        .addAnnotation("endRepeat")
        .addNote(0, "A3", "4.", { stem: "up" }).addAnnotation("Am", "chordLabel")
        .addNote(0, "A3", "4n")
        .addNote(0, "A3", "8n")
        .addNote(1, "A2", "8n", { stem: "down" })
        .addNote(1, "E3", "8n")
        .addNote(1, "C4", "8n")
        .addNote(1, "A2", "4.")

        .addMeasure()
        .addAnnotation("ending", { endingPassages: 2 })
        .addNote(0, "A3", "4.", { stem: "up" }).addAnnotation("Am", "chordLabel")
        .addNote(0, "A3", "4.").addAnnotation("fermata")
        .addNote(1, "A2", "8n", { stem: "down" })
        .addNote(1, "E3", "8n")
        .addNote(1, "C4", "8n")
        .addNote(1, "A2", "4.")

        .getDocument();
}
