import * as Score from "web-music-score/score";

export function createAnnotationDynamicsDemo() {
    return new Score.DocumentBuilder()
        .setHeader("Annotation: Dynamics")
        .setScoreConfiguration("guitarTreble")

        .addMeasure()
        .setKeySignature("G", "Major")
        .setTimeSignature("4/4")
        .setTempo(70)
        .addNote(0, "G3", "8n", { stem: "up" }).addAnnotation("ppp")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G4", "8n").addAnnotation("pp", "dynamics")
        .addNote(0, "F#4", "8n")
        .addNote(0, "E4", "8n")
        .addNote(0, "D4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("p")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n").addAnnotation("mp")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "D4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("m")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n").addAnnotation("mf")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("f")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n").addAnnotation("ff")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("fff")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "2n")

        .addMeasure()
        .addNote(0, "G3", "8n").addSpan("dim.", span => span.infinity())
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G4", "8n")
        .addNote(0, "F#4", "8n")
        .addNote(0, "E4", "8n")
        .addNote(0, "D4", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("ppp")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addSpan("cresc.", span => span.infinity())
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("fff")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("mf")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addSpan("cresc.", span => span.notes("1n"))
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "F#4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addSpan("dim.", span => span.notes("1n"))
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n").addSpan("dim.", span => span.notes("2n"))
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "E4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("ff")

        .addMeasure()
        .addNote(0, "G3", "8n").addSpan("dim.", span => span.notes("2n"))
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n").addAnnotation("fff")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("pp")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n").addSpan("cresc.", span => span.notes("2n"))
        .addNote(0, "E4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "C4", "4n").addAnnotation("pp")

        .getDocument();
}
