import * as Score from "web-music-score/score";

export function createAnnotationHairpinDemo() {
    return new Score.DocumentBuilder()
        .setHeader("Annotation: Hairpin")
        .setScoreConfiguration("guitarTreble")

        .addMeasure()
        .setKeySignature("G", "Major")
        .setTimeSignature("4/4")
        .setTempo(70)
        .addNote(0, "G3", "8n", { stem: "up" }).addAnnotation("ppp")
        .addNote(0, "A3", "8n").addSpan("<", span => span.infinity())
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G4", "8n")
        .addNote(0, "F#4", "8n")
        .addNote(0, "E4", "8n")
        .addNote(0, "D4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "D4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("fff")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "2n")

        .addMeasure()
        .addNote(0, "G3", "8n").addSpan(">", span => span.infinity())
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G4", "8n")
        .addNote(0, "F#4", "8n")
        .addNote(0, "E4", "8n")
        .addNote(0, "D4", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("ppp")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addSpan("<", span => span.infinity())
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("fff")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("p")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addSpan("<", span => span.notes("1n"))
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "F#4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addSpan(">", span => span.notes("1n"))
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .getDocument();
}
