import * as Score from "web-music-score/score";

export function createDeprecatedTestsDemo() {
    return new Score.DocumentBuilder()
        .setHeader("Deprecated Tests")
        .setScoreConfiguration([
            { type: "staff", clef: "G" },
            { type: "staff", clef: "G" },
        ])

        .addStaffGroup("grpAbove", 1, "above")
        .addStaffGroup("grpBelow", 1, "below")


        .addStaffGroup("grpAbove0", 0, "above")
        .addStaffGroup("grpBelow1", 1, "below")
        .addStaffGroup("grpBoth", ["grpAbove0", "grpBelow1"])

        .setKeySignature("C", "Major")
        .setTimeSignature("C")
        .setTempo(160)

        // --- Deprecated and Non-Deprecated Navigation Tests ---
        .addMeasure()
        .addLyrics(1, "1. EndRepeat", "1n", { align: "left" })
        .addNavigation("startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addNavigation("endRepeat", 2)
        .addMeasure()
        .addLyrics(1, "2. EndRepeat", "1n", { align: "left" })
        .addNavigationTo(1, "startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addNavigationTo(1, "endRepeat", 3)
        .addMeasure()
        .addLyrics(1, "3. EndRepeat", "1n", { align: "left" })
        .addAnnotation("startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addAnnotationTo(1, "endRepeat", { repeatCount: 4 })
        .addMeasure()
        .addLyrics(1, "4. EndRepeat", "1n", { align: "left" })
        .addAnnotation("startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addAnnotationTo(1, "endRepeat", { repeatCount: 5 })
        .endRow()

        .addMeasure()
        .addLyrics(1, "1. Ending", "1n", { align: "left" })
        .addNavigation("startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addNavigation("endRepeat")
        .addNavigation("ending", 1, 2)
        .addMeasure()
        .addNavigationTo(1, "startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addNavigationTo(1, "ending", 3)
        .addMeasure()
        .addLyrics(1, "2. Ending", "1n", { align: "left" })
        .addAnnotation("startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addNavigation("endRepeat")
        .addAnnotation("ending", { endingPassages: [1, 2] })
        .addMeasure()
        .addAnnotationTo(1, "startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addAnnotationTo(1, "ending", { endingPassages: 3 })
        .addMeasure()
        .addLyrics(1, "3. Ending", "1n", { align: "left" })
        .addAnnotation("startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addNavigation("endRepeat")
        .addAnnotation("ending", { endingPassages: [1, 2] })
        .addMeasure()
        .addAnnotationTo(1, "startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addAnnotationTo(1, "ending", { endingPassages: 3 })
        .endRow()

        .addMeasure()
        .addLyrics(1, "1. Any text", "1n", { align: "left" })
        .addNote(0, "G4", "2n").addAnnotation("any text", { group: "dynamics" })
        .addNote(0, "G4", "2n")
        .addMeasure()
        .addLyrics(1, "2. Any text", "1n", { align: "left" })
        .addNote(0, "G4", "2n").addAnnotation("any text", { group: "dynamics" })
        .addNote(0, "G4", "2n")
        .endRow()

        .addMeasure()
        .addLyrics(1, "1. No depr. just testing", "1n", { align: "left" })
        .addNote(0, "G4", "4n").addAnnotation("pitchLabel", { group: "pitchLabel" })
        .addNote(0, "G4", "4n").addAnnotation("pitchLabel", { group: "pitchLabel" })
        .addNote(0, "G4", "4n").addAnnotation("chordLabel", { group: "chordLabel" })
        .addNote(0, "G4", "4n").addAnnotation("chordLabel", { group: "chordLabel" })

        .getDocument();
}
