import * as Score from "web-music-score/score";

export function createAnnotationTempoDemo() {
    return new Score.DocumentBuilder()
        .setHeader("Annotation: Tempo")
        .setScoreConfiguration("guitarTreble")

        .addMeasure()
        .setKeySignature("G", "Major")
        .setTimeSignature("4/4")
        .setTempo(70)
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n").addAnnotation("tempo", "accel.").addExtension(ext => ext.notes("2n"))
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("tempo", "a tempo")

        .addMeasure()
        .setTempo(80)
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("tempo", "rit.").addExtension(ext => ext.notes("1n"))
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "D4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("tempo", "a tempo")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("tempo", "accel.").addExtension(ext => ext.infinity().hide())
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n").addAnnotation("tempo", "a tempo")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("tempo", "accel.").addExtension(ext => ext.notes("1n", 3))
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "F#4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n").addAnnotation("tempo", "a tempo")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("tempo", "accel.").addExtension(ext => ext.measures(2))
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "E4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .getDocument();
}
