import * as Score from "@tspro/web-music-score/score";

export function createBeamDetectionDemo() {
    return new Score.DocumentBuilder()
        .setHeader("Beam Detection")
        .setScoreConfiguration("guitarTreble")

        .addMeasure()
        .setKeySignature("G", "Major")
        .setTimeSignature("2/4")
        .setTempo(80)
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "8n")

        .addMeasure()
        .addNote(0, "G3", "4n")
        .addNote(0, "G3", "4n")

        .addMeasure()
        .addNote(0, "G3", "4n")
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "4n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "4n")
        .addNote(0, "G3", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "8n")
        .endRow()

        .addMeasure()
        .addRest(0, "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "8n")
        .addRest(0, "8n")

        .addMeasure()
        .addNote(0, "G3", "8.")
        .addNote(0, "G3", "16n")
        .addNote(0, "G3", "16n")
        .addNote(0, "G3", "8.")

        .addMeasure()
        .addNote(0, "G3", "8..")
        .addNote(0, "G3", "32n")
        .addNote(0, "G3", "64n")
        .addNote(0, "G3", "8...")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "16n")
        .addNote(0, "G3", "16n")
        .addNote(0, "G3", "16n")
        .addNote(0, "G3", "16n")
        .addNote(0, "G3", "8n")

        .addMeasure()
        .addNote(0, "G3", "32n")
        .addNote(0, "G3", "32n")
        .addNote(0, "G3", "16n")
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "16n")
        .addNote(0, "G3", "32n")
        .addNote(0, "G3", "32n")
        .endRow()

        // Test different time signatures

        .addMeasure()
        .setTimeSignature("2/4")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")

        .addMeasure()
        .setTimeSignature("3/4")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")

        .addMeasure()
        .setTimeSignature("4/4")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")

        .addMeasure()
        .setTimeSignature("3/8")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")

        .addMeasure()
        .setTimeSignature("5/8", "2-3")
        .addNote(0, "G3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "D4", "8n")
        .endRow()

        .addMeasure()
        .setTimeSignature("5/8", "3-2")
        .addNote(0, "G3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "D4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "B3", "8n")

        .addMeasure()
        .setTimeSignature("6/8")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")

        .addMeasure()
        .setTimeSignature("7/8", "2-2-3")
        .addNote(0, "G3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "D4", "8n")

        .addMeasure()
        .setTimeSignature("7/8", "3-2-2")
        .addNote(0, "G3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "D4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "B3", "8n")
        .endRow()

        .addMeasure()
        .setTimeSignature("9/8")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")

        .addMeasure()
        .setTimeSignature("12/8")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .endRow()


        // Test beams fail cases

        .addMeasure()
        .setTimeSignature("3/4")
        .addNote(0, "G3", "32n")
        .addNote(0, "G3", "16n")
        .addNote(0, "G3", "32n")
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "32n")
        .addNote(0, "G3", "8n")
        .addNote(0, "G3", "32n")
        .addNote(0, "G3", "16n")

        .addMeasure()
        .setTimeSignature("6/8")
        .addNote(0, "G3", "8.")
        .addNote(0, "G3", "8.")
        .addNote(0, "G3", "16n")
        .addNote(0, "G3", "16n")

        .getDocument();
}
