import * as Score from "@tspro/web-music-score/score";

export function createConnectivesDemo() {
    return new Score.DocumentBuilder()
        .setHeader("Connectives")
        .setScoreConfiguration("treble")

        .addMeasure()
        .setTimeSignature("4/4")
        .addNote(0, "G4", "4n", { stem: "up" }).addConnective("slur", 2, "below")
        .addNote(0, "A4", "4n", { stem: "up" })
        .addNote(0, "G4", "4n", { stem: "down" }).addConnective("slur", 2, "below")
        .addNote(0, "A4", "4n", { stem: "down" })

        .addMeasure()
        .addNote(0, "G4", "4n", { stem: "up" }).addConnective("slur", 2, "above")
        .addNote(0, "A4", "4n", { stem: "up" })
        .addNote(0, "G4", "4n", { stem: "down" }).addConnective("slur", 2, "above")
        .addNote(0, "A4", "4n", { stem: "down" })

        .addMeasure()
        .addNote(0, "G4", "4n", { stem: "up" }).addConnective("slur", 2, "center")
        .addNote(0, "A4", "4n", { stem: "up" })
        .addNote(0, "G4", "4n", { stem: "down" }).addConnective("slur", 2, "center")
        .addNote(0, "A4", "4n", { stem: "down" })

        .addMeasure()
        .addNote(0, "G4", "4n", { stem: "up" }).addConnective("slur", 2, "stemTip")
        .addNote(0, "A4", "4n", { stem: "up" })
        .addNote(0, "G4", "4n", { stem: "down" }).addConnective("slur", 2, "stemTip")
        .addNote(0, "A4", "4n", { stem: "down" })
        .endRow()

        .addMeasure()
        .setKeySignature("D", "Major")
        .setTimeSignature("3/4")
        .addNote(1, "G3", "2.", { stem: "down" })
        .addRest(0, "4n", { staffPos: "D5" })
        .addChord(0, ["A4", "B4"], "4n", { stem: "up" }).addConnective("tie")
        .addChord(0, ["G4", "B4"], "4n")

        .addMeasure()
        .addNote(1, "D4", "2.", { stem: "down" }).addConnective("tie", 2, "below")
        .addRest(0, "2n", { staffPos: "D5" })
        .addChord(0, ["A4", "C#5", "F#5"], "4n", { stem: "up" }).addConnective("tie", 2)

        .addMeasure()
        .addNote(1, "D4", "2.", { stem: "down" })
        .addChord(0, ["A4", "C#5", "F#5"], "2.", { stem: "up" })

        .addMeasure()
        .addNote(0, "D4", "2.").addConnective("tie", 3)
        .endRow()

        .addMeasure()
        .addNote(0, "D4", "2.")

        .addMeasure()
        .addNote(0, "D4", "2.")
        .endRow()

        .addMeasure()
        .setKeySignature("E", "Major")
        .setTimeSignature("4/4")
        .addNote(0, "E4", "8n").addConnective("slur", 2)
        .addNote(0, "F#4", "8n")
        .addNote(0, "G#4", "8n").addConnective("slur", 2)
        .addNote(0, "A4", "8n")
        .addNote(0, "B4", "8n").addConnective("slur", 4)
        .addNote(0, "C#5", "8n")
        .addNote(0, "D#5", "8n")
        .addNote(0, "E5", "8n")

        .addMeasure()
        .addNote(0, "E4", "8n").addConnective("slur", 8)
        .addNote(0, "F#4", "8n").addConnective("slur", 2)
        .addNote(0, "G#4", "8n")
        .addNote(0, "A4", "8n").addConnective("slur", 2)
        .addNote(0, "B4", "8n")
        .addNote(0, "C#5", "8n").addConnective("slur", 2)
        .addNote(0, "D#5", "8n")
        .addNote(0, "E5", "8n")
        .endRow()

        .addMeasure()
        .setTimeSignature("3/4")
        .setKeySignature("C", "Major")
        .addNote(0, "A4", "2n")
        .addNote(0, "E5", "4n")
        .addNote(1, "A3", "4n", { stem: "down" }).addConnective("tie", "stub", "below")
        .addNote(1, "E4", "2n")

        .addMeasure()
        .addNote(0, "A4", "8n")
        .addNote(0, "E4", "8n")
        .addNote(0, "A4", "8n")
        .addNote(0, "B4", "8n").addConnective("tie", "toMeasureEnd")
        .addNote(0, "C5", "8n").addConnective("tie", "toMeasureEnd")
        .addNote(0, "E5", "8n").addConnective("tie", "toMeasureEnd")
        .addNote(1, "A3", "2.").addConnective("tie", 2, "below")

        .addMeasure()
        .addNote(0, "A4", "2.")
        .addNote(1, "A3", "2.")
        .endRow()

        .addMeasure()
        .addNote(0, "F4", "4n", { stem: "up" }).addConnective("slide", "center")
        .addNote(0, "A4", "4n", { stem: "up" })
        .addNote(0, "F4", "4n", { stem: "down" }).addConnective("slide", "center")
        .addNote(0, "A4", "4n", { stem: "down" })

        .addMeasure()
        .addNote(0, "F4", "4n", { stem: "up" }).addConnective("slide", "below")
        .addNote(0, "A4", "4n", { stem: "up" })
        .addNote(0, "F4", "4n", { stem: "down" }).addConnective("slide", "above")
        .addNote(0, "A4", "4n", { stem: "down" })

        .getDocument();
}
