import * as Score from "web-music-score/score";

export function createDeprecatedTestsDemo() {
    return new Score.DocumentBuilder()
        .setHeader("Deprecated Tests")
        .setScoreConfiguration([
            { type: "staff", clef: "G" },
            { type: "staff", clef: "G" },
        ])

        .addStaffGroup("grpAbove", 1, "above")
        .addStaffGroup("grpBelow", 1, "below")


        .addStaffGroup("grpAbove0", 0, "above")
        .addStaffGroup("grpBelow1", 1, "below")
        .addStaffGroup("grpBoth", ["grpAbove0", "grpBelow1"])

        .setKeySignature("C", "Major")
        .setTimeSignature("C")
        .setTempo(160)

        // --- Deprecated and Non-Deprecated Label Tests ---
        .addLyrics(1, "1. Label", "1n", { align: "left" })
        .addNote(0, "B3", "4n").addLabel("note", "B3")
        .addNote(0, "E5", "4n").addLabelTo("grpBelow", "note", "E5")
        .addChord(0, ["C4", "E4", "G4"], "4n").addLabel("chord", "C")
        .addChord(0, ["A4", "C5", "E5"], "4n").addLabelTo("grpAbove", "chord", "Am")
        .addMeasure()
        .addLyrics(1, "2. Label", "1n", { align: "left" })
        .addNote(0, "B3", "4n").addAnnotation("pitchLabel", "B3")
        .addNote(0, "E5", "4n").addAnnotationTo("grpBelow", "pitchLabel", "E5")
        .addChord(0, ["C4", "E4", "G4"], "4n").addAnnotation("chordLabel", "C")
        .addChord(0, ["A4", "C5", "E5"], "4n").addAnnotationTo("grpAbove", "chordLabel", "Am")
        .endRow()

        // --- Deprecated and Non-Deprecated Fermata Tests ---
        .addMeasure()
        .addLyrics(1, "1. Fermata", "1n", { align: "left" })
        .addNote(0, "C4", "4n").addFermata("atNote")
        .addNote(0, "E4", "4n").addFermataTo("grpBelow", "atNote")
        .addNote(0, "G4", "4n").addFermataTo("grpBoth", "atMeasureEnd")
        .addNote(0, "C5", "4n")
        .addMeasure()
        .addLyrics(1, "2. Fermata", "1n", { align: "left" })
        .addNote(0, "C4", "4n").addAnnotation("articulation", "fermata")
        .addNote(0, "E4", "4n").addAnnotationTo("grpBelow", "articulation", "fermata")
        .addNote(0, "G4", "4n").addAnnotationTo("grpBoth", "measureEndFermata")
        .addNote(0, "C5", "4n")
        .addMeasure()
        .addLyrics(1, "3. Fermata", "1n", { align: "left" })
        .addNote(0, "C4", "4n").addAnnotation("fermata")
        .addNote(0, "E4", "4n").addAnnotationTo("grpBelow", "fermata")
        .addNote(0, "G4", "4n").addAnnotationTo("grpBoth", "fermata", { anchor: "rightBarLine" })
        .addNote(0, "C5", "4n")
        .endRow()

        // --- Deprecated and Non-Deprecated Navigation Tests ---
        .addMeasure()
        .addLyrics(1, "1. EndRepeat", "1n", { align: "left" })
        .addNavigation("startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addNavigation("endRepeat", 2)
        .addMeasure()
        .addLyrics(1, "2. EndRepeat", "1n", { align: "left" })
        .addNavigationTo(1, "startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addNavigationTo(1, "endRepeat", 3)
        .addMeasure()
        .addLyrics(1, "3. EndRepeat", "1n", { align: "left" })
        .addAnnotation("startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addAnnotationTo(1, "endRepeat", 4)
        .addMeasure()
        .addLyrics(1, "4. EndRepeat", "1n", { align: "left" })
        .addAnnotation("startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addAnnotationTo(1, "endRepeat", { repeatCount: 5 })
        .endRow()

        .addMeasure()
        .addLyrics(1, "1. Ending", "1n", { align: "left" })
        .addNavigation("startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addNavigation("ending", 1, 2)
        .addMeasure()
        .addNavigationTo(1, "startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addNavigationTo(1, "ending", 3)
        .addMeasure()
        .addLyrics(1, "2. Ending", "1n", { align: "left" })
        .addAnnotation("startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addAnnotation("ending", 1, 2)
        .addMeasure()
        .addAnnotationTo(1, "startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addAnnotationTo(1, "ending", 3)
        .addMeasure()
        .addLyrics(1, "3. Ending", "1n", { align: "left" })
        .addAnnotation("startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addAnnotation("ending", { endingPassages: [1, 2] })
        .addMeasure()
        .addAnnotationTo(1, "startRepeat")
        .addNote(0, "C4", "4n")
        .addNote(0, "E4", "4n")
        .addNote(0, "G4", "4n")
        .addNote(0, "C5", "4n")
        .addAnnotationTo(1, "ending", { endingPassages: 3 })

        .getDocument();
}
