import * as Score from "@tspro/web-music-score/score";

export function createDynamicsAnnotationDemo() {
    return new Score.DocumentBuilder()
        .setHeader("Dynamics Annotation")
        .setScoreConfiguration("guitarTreble")

        .addMeasure()
        .setKeySignature("G", "Major")
        .setTimeSignature("4/4")
        .setTempo(70)
        .addNote(0, "G3", "8n", { stem: "up" }).addAnnotation("dynamics", "ppp")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G4", "8n").addAnnotation("dynamics", "pp")
        .addNote(0, "F#4", "8n")
        .addNote(0, "E4", "8n")
        .addNote(0, "D4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "p")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "mp")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "D4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "m")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "mf")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "f")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "ff")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "fff")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "2n")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "dim.").addExtension(ext => ext.infinity())
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G4", "8n")
        .addNote(0, "F#4", "8n")
        .addNote(0, "E4", "8n")
        .addNote(0, "D4", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("dynamics", "ppp")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "cresc.").addExtension(ext => ext.infinity())
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("dynamics", "fff")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "mf")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "cresc.").addExtension(ext => ext.notes("1n"))
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "F#4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "dim.").addExtension(ext => ext.notes("1n"))
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .endRow()

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "dim.").addExtension(ext => ext.notes("2n"))
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "E4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n").addAnnotation("dynamics", "ff")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "dim.").addExtension(ext => ext.notes("2n"))
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "fff")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n")
        .addNote(0, "C4", "8n")

        .addMeasure()
        .addNote(0, "G3", "8n").addAnnotation("dynamics", "pp")
        .addNote(0, "A3", "8n")
        .addNote(0, "B3", "8n").addAnnotation("dynamics", "cresc.").addExtension(ext => ext.notes("2n"))
        .addNote(0, "E4", "8n")
        .addNote(0, "G3", "8n")
        .addNote(0, "A3", "8n")
        .addNote(0, "C4", "4n").addAnnotation("dynamics", "pp")

        .getDocument();
}
